export { Schedule } from './Schedule/Schedule.jsx'
export { ConsultingRooms } from './ConsultingRooms/ConsultingRooms.jsx'
export { Doctor } from './Doctor/Doctor.jsx'
export { DoctorsList } from './DoctorsList/DoctorsList.jsx'
export { Specialty } from './Specialty/Specialty.jsx'
export { Login } from './Login/Login.jsx'
export { UserAdd } from './UserAdd/UserAdd.jsx'
