export { Schedule } from './Schedule/Schedule.jsx'
export { ScheduleAppointments } from './ScheduleAppointments/ScheduleAppointments.jsx'
export { ConsultingRooms } from './ConsultingRooms/ConsultingRooms.jsx'
export { Doctor } from './Doctor/Doctor.jsx'
export { DoctorsList } from './DoctorsList/DoctorsList.jsx'
export { DoctorList} from './DoctorList/DoctorList.jsx'
export { Specialty } from './Specialty/Specialty.jsx'
export { Login } from './Login/Login.jsx'
export { Users } from './Users/Users.jsx'
